---
title: "Data Compiling and Cleaning"
format: html
---

0 - OLD FORGE
1 - FISH CREEK/REMSEN
2 - PLATTSBURGH
```{r}
library(tidyverse)
```

```{r}
day1 <- read.csv("data/day1.csv") |> filter(year > 2007)
day2 <- read.csv("data/day2.csv") |> filter(year > 2007)
day3 <- read.csv("data/day3.csv") |> filter(year > 2007)
weather <- read.csv("data/weather.csv")
water <- read.csv("data/water_level.csv")
dates <- read.csv("data/dates.csv")

dates <- dates |> select(day.1, day.2, day.3) |>
  mutate(day.1 = mdy(day.1), day.2 = mdy(day.2), day.3 = mdy(day.3))

weather <- weather |> mutate(time = ymd(time))
```

```{r}
day1_weather <- weather |> filter(time %in% dates$day.1 & location_id == 0) |>
  mutate(time = year(time))

day2_weather <- weather |> filter(time %in% dates$day.2 & location_id == 1) |>
  mutate(time = year(time))

day3_weather <- weather |> filter(time %in% dates$day.3 & location_id == 2) |>
  mutate(time = year(time))
```

```{r}
day1 <- left_join(day1, day1_weather, join_by(year == time))
day2 <- left_join(day2, day2_weather, join_by(year == time))
day3 <- left_join(day3, day3_weather, join_by(year == time))
```

```{r}
day1_full <- left_join(day1, water) |> select(!location_id & !day2 & !day3)
day2_full <- left_join(day2, water) |> select(!location_id & !day1 & !day3)
day3_full <- left_join(day3, water) |> select(!location_id & !day1 & !day2)
```

```{r}
day1_full <- day1_full |> 
  rename(temp = temperature_2m_mean...F.) |>
  rename(rain = precipitation_sum..inch.) |>
  rename(water = day1) |>
  mutate(value = value / 3600)

day2_full <- day2_full |> 
  rename(temp = temperature_2m_mean...F.) |>
  rename(rain = precipitation_sum..inch.) |>
  rename(water = day2) |> 
  mutate(value = value / 3600)

day3_full <- day3_full |> 
  rename(temp = temperature_2m_mean...F.) |>
  rename(rain = precipitation_sum..inch.) |>
  rename(water = day3) |> 
  mutate(value = value / 3600)

```

```{r}
day1_full <- day1_full |> filter(boatType != "Unknown") |> 
  mutate(boatType = if_else(classId == "voyageur",
                            "Voyageur",
                            boatType)) |>
  mutate(n_paddler = case_when(
    str_detect(classId, "1") ~ 1,
    str_detect(classId, "2") ~ 2,
    str_detect(classId, "3") ~ 3,
    str_detect(classId, "4") ~ 4,
    boatType == "SUP" ~ 1,
    .default = 6
  ))

day2_full <- day2_full |> filter(boatType != "Unknown") |>
  mutate(boatType = if_else(classId == "voyageur",
                            "Voyageur",
                            boatType)) |>
  mutate(n_paddler = case_when(
    str_detect(classId, "1") ~ 1,
    str_detect(classId, "2") ~ 2,
    str_detect(classId, "3") ~ 3,
    str_detect(classId, "4") ~ 4,
    boatType == "SUP" ~ 1,
    .default = 6
  ))

day3_full <- day3_full |> filter(boatType != "Unknown") |>
  mutate(boatType = if_else(classId == "voyageur",
                            "Voyageur",
                            boatType)) |>
  mutate(n_paddler = case_when(
    str_detect(classId, "1") ~ 1,
    str_detect(classId, "2") ~ 2,
    str_detect(classId, "3") ~ 3,
    str_detect(classId, "4") ~ 4,
    boatType == "SUP" ~ 1,
    .default = 6
  ))
```

```{r}
write_csv(day1_full, "data/day1_full.csv")
write_csv(day2_full, "data/day2_full.csv")
write_csv(day3_full, "data/day3_full.csv")
```



